//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACApplication
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> ACApplicationCategory_ID { get; set; }
        public string Developer { get; set; }
    
        public virtual ACApplicationCategory ACApplicationCategory { get; set; }
        public string SelectedItem { get; internal set; }
    }
}
